config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'

  get 'sessions/log_out' => 'sessions#destroy'

  get 'profiles' => 'profiles#index'

  get 'coverage_reports/find' => 'coverage_reports#find'
  post 'coverage_reports/share' => 'coverage_reports#share'

  resources :users
  resources :coverage_reports
  resources :hits

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :coverage_reports
  has_secure_password
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, :length => {
                                   :within => 8..25,
                                   :too_short => "Your password is too short. It must be between 8 and 25 characters.",
                                   :too_long => "Your password is too long. It must be between 8 and 25 characters."
                                  }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id].to_i)
    @coverage_reports = @user.coverage_reports.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user)
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns alpha">
    <h1 class="user_banner">Edit Your Account</h1>
    <div class="row"></div>
    <div class="eight columns alpha omega">
      <%= render 'form' %>
      <%= form_tag(user_path(@user), method: "delete") do %>
        <%= submit_tag "Delete Account" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row"></div>
<div class="container">
  <div class="thirteen columns offset-by-two">
    <h1>Coverage Reportr</h1>
    <h2>Serving Coverage Reports with Ease and Grace</h2>
    <div class="row"></div>
    <div class="five columns alpha nav_container">
      <%= form_tag(sessions_new_path, method: "get") do %>
        <%= submit_tag "Log In" %>
      <% end %>

      <%= form_tag(new_user_path, method: "get") do %>
        <%= submit_tag "Create Account" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns">
    <% if @user.errors.any? %>
      <div class="errors">
        <p style="font-weight:bold;">
          Oopsies! ...you did <%= pluralize(@user.errors.count, "bad thing") %>
        </p>
        <div class="row"></div>
        <ul class="error_list">
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row"></div>
    <h1>Create New Account</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns alpha omega">
    <h1 class="user_banner">
      <%= @user.username %> (<%= @user.email %>)
      <%= form_tag(edit_user_path(@user), method: "get") do %>
        <%= submit_tag "Edit Account" %>
      <% end %>
      <%= form_tag(sessions_log_out_path, method: "get") do %>
        <%= submit_tag "Log Out" %>
      <% end %>
    </h1>

    <div class="row"></div>

    <div class="sixteen columns alpha omega hits_table">
      <table>
        <tr>
          <th class="left_row">Coverage Report Name</th>
          <th class="right_row">Do the Stuff</th>
        </tr>
        <% @coverage_reports.each do |report| %>
          <tr>
            <td class="left_row">
              <%= report.company_name %>: <%= report.announcement %>
            </td>
            <td class="right_row">
              <%= form_tag(coverage_report_path(report), method: "get") do %>
                <%= hidden_field_tag :user_id, @user.id %>
                <%= submit_tag "View" %>
              <% end %>
              <%= form_tag(edit_coverage_report_path(report), method: "get") do %>
                <%= hidden_field :user, :id %>
                <%= submit_tag "Edit" %>
              <% end %>
              <%= form_tag(coverage_report_path(report), method: "delete") do %>
                <%= hidden_field :user, :id %>
                <%= submit_tag "Delete" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

      <div class="row"></div>
      <%= form_tag(new_coverage_report_path, method: "get") do %>
        <%= hidden_field :user, :id %>
        <%= submit_tag "New Coverage Report" %>
      <% end %>
    </div>
  </div>
</div>