config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'

  get 'sessions/log_out' => 'sessions#destroy'

  get 'profiles' => 'profiles#index'

  get 'coverage_reports/find' => 'coverage_reports#find'
  post 'coverage_reports/share' => 'coverage_reports#share'

  resources :users
  resources :coverage_reports
  resources :hits

end

app/models/coverage_report.rb
class CoverageReport < ActiveRecord::Base
  has_and_belongs_to_many :coverage_reports
  has_many :hits
end

app/controllers/coverage_reports_controller.rb
class CoverageReportsController < ApplicationController

  def new
    @user = User.find(params[:user][:id].to_i)
    @coverage_report = CoverageReport.new
  end

  def create
    @user = User.find(params[:user][:id].to_i)
    @coverage_report = CoverageReport.create(coverage_report_params)
    @user.coverage_reports << @coverage_report
    redirect_to coverage_report_path(@coverage_report, user_id: @user.id)
  end

  def show
    @user = User.find(params[:user_id].to_i)
    @coverage_report = CoverageReport.find(params[:id])
    @coverage_reports = @user.coverage_reports.all
    @hits = @coverage_report.hits
  end

  def edit
    @user = User.find(params[:user][:id].to_i)
    @coverage_report = CoverageReport.find(params[:id])
  end

  def update
    @user = User.find(params[:user][:id].to_i)
    coverage_report = CoverageReport.find(params[:id])
    coverage_report.update(coverage_report_params)
    redirect_to coverage_report_path(coverage_report, user_id: @user.id)
  end

  def destroy
    @user = User.find(params[:user][:id].to_i)
    coverage_report = CoverageReport.find(params[:id].to_i)
    coverage_report.delete
    redirect_to user_path(@user)
  end

  def find
    @new_user = User.new
    @user = User.find(params[:user][:id].to_i)
    @coverage_report = CoverageReport.find(params[:coverage_report][:id].to_i)
  end

  def share
    @user = User.find(params[:user][:id].to_i)
    @new_user = User.find_by email: params['new_user']['email']
    @coverage_report = CoverageReport.find(params[:coverage_report][:id].to_i)
    @new_user.coverage_reports << @coverage_report
  end

  private

  def coverage_report_params
    params.require(:coverage_report).permit(:company_name, :announcement)
  end

end

app/views/coverage_reports/_form.html.erb
<%= form_for @coverage_report do |f| %>
  <%= f.label :company_name %>
  <%= f.text_field :company_name %>
  <%= f.label :announcement %>
  <%= f.text_field :announcement %>
  <%= hidden_field :user, :id %>
  <%= f.submit %>
<% end %>

app/views/coverage_reports/edit.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns">

    <h1 class="user_banner">
      <%= @user.username %> (<%= @user.email %>)
    </h1>

    <div class="row"></div>

    <h2>Edit Coverage Report</h2>
    <%= render 'form' %>

  </div>
</div>

app/views/coverage_reports/find.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns">
    <h1>Enter the User's Email Below</h1>

    <%= form_tag(coverage_reports_share_path, method: "post") do %>
      <%= text_field :new_user, :email %>
      <%= hidden_field :user, :id %>
      <%= hidden_field :coverage_report, :id %>
      <%= submit_tag "Find User" %>
    <% end %>
  </div>
</div>

app/views/coverage_reports/new.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns">

    <h1 class="user_banner">
      <%= @user.username %> (<%= @user.email %>)
    </h1>

    <div class="row"></div>

    <h2>Create New Coverage Report</h2>
    <%= render 'form' %>

  </div>
</div>

app/views/coverage_reports/share.html.erb
<div class="row"></div>
<div class="container">
  <div class="sixteen columns">
    <h1>Sweet, this coverage report was shared with <%= @new_user.username %></h1>

    <%= form_tag(coverage_report_path(@coverage_report), method: "get") do %>
      <%= hidden_field_tag :user_id, @user.id %>
      <%= hidden_field :coverage_report, :id %>
      <%= submit_tag "Back to Coverage Report" %>
    <% end %>
  </div>
</div>

app/views/coverage_reports/show.html.erb
<div class="row"></div>

<div class="container">
  <div class="sixteen columns alpha omega">
    <h1 class="user_banner">
      <%= @user.username %> (<%= @user.email %>)
      <%= form_tag(user_path(@user), method: "get") do %>
        <%= hidden_field :user, :id %>
        <%= submit_tag "See All My Reports" %>
      <% end %>
    </h1>
  </div>

  <div class="row"></div>

  <div class="sixteen columns alpha omega cr-title">
    <h1><%= @coverage_report.company_name %></h1>
    <h3><%= @coverage_report.announcement %></h3>
  </div>

  <div class="row"></div>

  <div class="sixteen columns alpha omega hits_table_options">
    <%= form_tag(new_hit_path, method: "get") do %>
      <%= hidden_field :user, :id %>
      <%= hidden_field :coverage_report, :id %>
      <%= submit_tag "Add New Hit"%>
    <% end %>

    <%= form_tag(hits_path, method: "get") do %>
      <%= hidden_field :user, :id %>
      <%= hidden_field :coverage_report, :id %>
      <%= submit_tag "Download to .csv"%>
    <% end %>

    <%= form_tag(coverage_reports_find_path, method: "get") do %>
      <%= hidden_field :user, :id %>
      <%= hidden_field :coverage_report, :id %>
      <%= submit_tag "Share"%>
    <% end %>
  </div>

  <div class="sixteen columns alpha hits_table">
    <table>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th class="url_column">URL</th>
        <th>Options</th>
      </tr>
      <% @hits.each do |hit| %>
        <tr>
          <td><%= hit.hit_title %></td>
          <td><%= hit.hit_author %></td>
          <td class="url_column"><a href="<%= hit.hit_url %>"><%= hit.hit_url %></a></td>
          <td class="hit_options">
            <%= form_tag(edit_hit_path(hit), method: "get") do %>
              <%= hidden_field_tag :user_id, @user.id %>
              <%= hidden_field_tag :coverage_report_id, @coverage_report.id %>
              <%= submit_tag "Edit Hit"%>
            <% end %>
            <%= form_tag(hit_path(hit), method: "delete") do %>
              <%= hidden_field :user, :id %>
              <%= hidden_field :coverage_report, :id %>
              <%= submit_tag "Delete Hit"%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="row"></div>
</div>